(() => {
  'use strict';
  const $ = (s, root = document) => root.querySelector(s);
  const $$ = (s, root = document) => [...root.querySelectorAll(s)];
  const DAYS = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'];
  const DAY_NAMES = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'];
  const apiBaseUrl = (window.MEDITRACK_API_URL || '').replace(/\/$/, '');
  let state = { user: null, medications: [], today: [], history: [], analytics: null, patients: [] };
  let chart;
  const escapeHTML = (value = '') => String(value).replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
  const dateKey = () => new Intl.DateTimeFormat('en-CA', { year: 'numeric', month: '2-digit', day: '2-digit' }).format(new Date());
  const timeLabel = time => { const [h, m] = time.split(':').map(Number); const d = new Date(); d.setHours(h, m); return d.toLocaleTimeString([], { hour: 'numeric', minute: '2-digit' }); };
  const dateLabel = date => new Date(`${date}T12:00:00`).toLocaleDateString(undefined, { month: 'short', day: 'numeric', year: 'numeric' });
  const statusMarkup = status => `<span class="status-badge status-${String(status).toLowerCase()}">${escapeHTML(status[0] + status.slice(1).toLowerCase())}</span>`;
  const csrf = () => document.cookie.split('; ').find(row => row.startsWith('csrf='))?.split('=').slice(1).join('') || '';
  async function api(path, options = {}) {
    const headers = { Accept: 'application/json', ...(options.headers || {}) };
    if (options.body) headers['Content-Type'] = 'application/json';
    if (!['GET', 'HEAD'].includes((options.method || 'GET').toUpperCase())) headers['X-CSRF-Token'] = csrf();
    const res = await fetch(`${apiBaseUrl}/api${path}`, { ...options, headers, credentials: 'same-origin' });
    const body = res.status === 204 ? null : await res.json().catch(() => ({}));
    if (!res.ok) { const err = new Error(body.error || 'The request could not be completed.'); err.status = res.status; throw err; }
    return body;
  }
  function toast(message, error = false) { const item = document.createElement('div'); item.className = `toast${error ? ' error' : ''}`; item.textContent = message; $('#toast-region').append(item); setTimeout(() => item.remove(), 4000); }
  function setBusy(button, busy, label) { if (!button) return; button.disabled = busy; if (busy) { button.dataset.label = button.textContent; button.textContent = label || 'Saving…'; } else if (button.dataset.label) button.textContent = button.dataset.label; }
  function showAuth(view = 'landing') { $('#app-shell').hidden = true; $('#auth-shell').hidden = false; ['landing', 'login', 'register'].forEach(name => { const node = $(`#${name}-panel`) || $(`#${name}-form`); if (node) node.hidden = name !== view; }); }
  function showApp() { $('#auth-shell').hidden = true; $('#app-shell').hidden = false; }
  function isPatient() { return state.user?.role === 'PATIENT'; }
  function renderHeader() {
    const user = state.user; if (!user) return;
    const hour = new Date().getHours(); const greeting = hour < 12 ? 'Good morning' : hour < 18 ? 'Good afternoon' : 'Good evening';
    $('#greeting').textContent = `${greeting}, ${user.name.split(' ')[0]}`; $('#today-label').textContent = new Date().toLocaleDateString(undefined, { weekday: 'long', month: 'long', day: 'numeric' }).toUpperCase();
    $('#profile-shortcut').textContent = user.name.charAt(0).toUpperCase(); $('#profile-shortcut').setAttribute('aria-label', `Open profile for ${user.name}`);
    $('#profile-name').value = user.name; $('#profile-email').value = user.email; $('#profile-role').value = user.role === 'PATIENT' ? 'Patient' : 'Caregiver';
    if ([...$('#timezone').options].some(o => o.value === user.timezone)) $('#timezone').value = user.timezone;
    const permission = 'Notification' in window ? Notification.permission : 'unavailable'; $('#notification-status').textContent = `Permission status: ${permission === 'granted' ? 'enabled' : permission === 'denied' ? 'blocked in browser settings' : permission === 'default' ? 'not requested' : 'unavailable'}`;
    $$('.patient-only').forEach(node => { node.hidden = !isPatient(); }); $('#patient-caregiver').hidden = !isPatient(); $('#caregiver-panel').hidden = isPatient();
  }
  function renderDashboard() {
    const doses = state.today; $('#today-count').textContent = doses.length; $('#taken-count').textContent = doses.filter(d => d.status === 'TAKEN').length; $('#weekly-score').textContent = state.analytics?.adherence == null ? '—' : `${state.analytics.adherence}%`;
    if (!isPatient()) { $('#home-subtitle').textContent = 'Review the patients who have shared access with you.'; $('#today-heading').textContent = 'Connected patients'; $('#today-list').innerHTML = state.patients.length ? state.patients.map(p => `<article class="medicine-item"><div class="dose-details"><strong>${escapeHTML(p.name)}</strong><span class="subline">${escapeHTML(p.email)}</span></div><button class="button secondary" data-patient="${p.id}">View activity</button></article>`).join('') : '<p class="empty-note">No patient has shared access with you yet.</p>'; $('#next-dose').innerHTML = '<p class="muted">Accept an invitation token in Caregiver access to view a patient.</p>'; return; }
    $('#home-subtitle').textContent = 'Your current medication plan.'; $('#today-heading').textContent = "Today's medicines";
    $('#today-list').innerHTML = doses.length ? doses.map(d => `<article class="dose-item"><time class="dose-time">${timeLabel(d.time)}</time><div class="dose-details"><strong>${escapeHTML(d.medication.name)}</strong><span>${escapeHTML(d.medication.dosage)}${d.medication.instructions ? ` · ${escapeHTML(d.medication.instructions)}` : ''}</span></div>${d.status === 'PENDING' ? `<div class="dose-actions"><button class="button primary" data-dose="${d.id}" data-status="TAKEN">Taken</button><button class="button secondary" data-dose="${d.id}" data-status="SKIPPED">Skip</button></div>` : statusMarkup(d.status)}</article>`).join('') : '<p class="empty-note">No medicines are scheduled today.</p>';
    const next = doses.find(d => d.status === 'PENDING'); $('#next-dose').innerHTML = next ? `<div class="reminder-card"><strong>${escapeHTML(next.medication.name)}</strong><span>${timeLabel(next.time)} · ${escapeHTML(next.medication.dosage)}</span></div>` : '<p class="muted">You’re all caught up.</p>';
  }
  function scheduleText(med) { return med.frequency === 'DAILY' ? 'Every day' : med.frequency === 'WEEKDAYS' ? 'Weekdays' : med.weekdays.map(d => DAY_NAMES[d]).join(', '); }
  function renderMedicines() { const list = $('#medicine-list'); if (!isPatient()) return; list.innerHTML = state.medications.length ? state.medications.map(m => `<article class="medicine-item"><div class="dose-details"><strong>${escapeHTML(m.name)} ${!m.isActive ? '<span class="status-badge status-pending">Inactive</span>' : ''}</strong><span class="subline">${escapeHTML(m.dosage)} · ${escapeHTML(scheduleText(m))} · ${m.times.map(timeLabel).join(', ')}</span>${m.instructions ? `<span class="subline">${escapeHTML(m.instructions)}</span>` : ''}<span class="subline">Starts ${dateLabel(m.startDate)}${m.endDate ? ` · Ends ${dateLabel(m.endDate)}` : ''}</span></div><div class="dose-actions"><button class="button secondary" data-edit="${m._id}">Edit</button><button class="button secondary" data-toggle="${m._id}">${m.isActive ? 'Pause' : 'Resume'}</button><button class="button secondary" data-delete="${m._id}">Delete</button></div></article>`).join('') : '<p class="empty-note">No medicines added yet.</p>'; }
  function renderHistory() { if (!isPatient()) return; const status = $('#status-filter').value, date = $('#date-filter').value; const rows = state.history.filter(d => (!date || d.date === date) && (status === 'ALL' || d.status === status)); $('#history-rows').innerHTML = rows.length ? rows.map(d => `<tr><td>${dateLabel(d.date)}</td><td>${escapeHTML(d.medication.name)}</td><td>${timeLabel(d.time)}</td><td>${statusMarkup(d.status)}</td></tr>`).join('') : '<tr><td class="empty-row" colspan="4">No dose activity found.</td></tr>'; }
  function renderAnalytics() { if (!isPatient() || !state.analytics) return; const a = state.analytics; $('#analytics-score').textContent = a.adherence == null ? '—' : `${a.adherence}%`; $('#analytics-taken').textContent = a.taken; $('#analytics-other').textContent = a.skipped + a.missed; $('#chart-empty').hidden = a.days.some(d => d.scheduled); if (!window.Chart) return; if (chart) chart.destroy(); chart = new Chart($('#adherence-chart'), { type: 'bar', data: { labels: a.days.map(d => new Date(`${d.date}T12:00:00`).toLocaleDateString(undefined, { weekday: 'short' })), datasets: [{ label: 'Adherence', data: a.days.map(d => d.adherence), backgroundColor: '#176b5b', borderRadius: 5, maxBarThickness: 34 }] }, options: { responsive: true, maintainAspectRatio: false, plugins: { legend: { display: false } }, scales: { y: { beginAtZero: true, max: 100, ticks: { callback: n => `${n}%` } }, x: { grid: { display: false } } } } }); }
  async function renderCaregiver() { if (!isPatient()) { $('#patient-list').innerHTML = state.patients.length ? `<div class="divider"></div><h3>Connected patients</h3>${state.patients.map(p => `<div class="connection-card"><div class="connection-main"><strong>${escapeHTML(p.name)}</strong><span class="subline">${escapeHTML(p.email)}</span></div><button class="text-button danger-text" data-revoke="${p.connectionId}">Remove access</button></div>`).join('')}` : '<p class="muted">No patient connections yet.</p>'; return; } try { const result = await api('/caregiver/connections'); const rows = result.connections; $('#connection-list').innerHTML = rows.length ? rows.map(link => `<div class="connection-card"><div class="connection-main"><strong>${escapeHTML(link.caregiver?.name || 'Caregiver')}</strong><span class="subline">${escapeHTML(link.caregiver?.email || '')} · ${link.status === 'ACTIVE' ? 'Connected' : 'Awaiting acceptance'}</span></div><button class="text-button danger-text" data-revoke="${link.id}">${link.status === 'ACTIVE' ? 'Revoke' : 'Cancel'}</button></div>`).join('') : '<p class="muted">No caregiver connected yet.</p>'; } catch (e) { $('#connection-list').innerHTML = `<p class="muted">${escapeHTML(e.message)}</p>`; } }
  function render() { renderHeader(); renderDashboard(); renderMedicines(); renderHistory(); renderAnalytics(); renderCaregiver(); }
  async function loadData() { if (!state.user) return; if (isPatient()) { const [meds, today, history, analytics] = await Promise.all([api('/medications'), api('/adherence/today'), api('/adherence/history?days=90'), api('/adherence/analytics')]); state.medications = meds.medications; state.today = today.doses; state.history = history.doses; state.analytics = analytics; } else { state.patients = (await api('/caregiver/patients')).patients; state.today = []; state.analytics = null; } render(); }
  function showView(name) { const allowed = isPatient() ? ['home', 'medicines', 'history', 'analytics', 'caregiver', 'profile'] : ['home', 'caregiver', 'profile']; if (!allowed.includes(name)) name = 'home'; $$('.view').forEach(v => v.classList.toggle('active', v.id === `view-${name}`)); $$('[data-view]').forEach(n => n.classList.toggle('active', n.dataset.view === name)); $('#page-title').textContent = ({ home: 'Overview', medicines: 'Medicines', history: 'History', analytics: 'Analytics', caregiver: 'Caregiver', profile: 'Profile & settings' })[name]; $('#more-menu').hidden = true; if (name === 'caregiver') renderCaregiver(); if (name === 'analytics') renderAnalytics(); }
  function route() { showView(location.hash.slice(1) || 'home'); }
  function initWeekdays(selected = []) { $('#weekday-picker').innerHTML = DAYS.map((d, i) => `<label class="day-chip"><input type="checkbox" value="${i}" ${selected.includes(i) ? 'checked' : ''} aria-label="${DAY_NAMES[i]}"><span>${d[0]}</span></label>`).join(''); }
  function openMedicine(med) { $('#medicine-form').reset(); $('#form-error').textContent = ''; $('#dialog-title').textContent = med ? 'Edit medicine' : 'Add medicine'; $('#medicine-id').value = med?._id || ''; $('#med-name').value = med?.name || ''; $('#med-dose').value = med?.dosage || ''; $('#med-frequency').value = med?.frequency || 'DAILY'; $('#med-times').value = med?.times?.join(', ') || ''; $('#med-start').value = med?.startDate || dateKey(); $('#med-end').value = med?.endDate || ''; $('#med-instructions').value = med?.instructions || ''; initWeekdays(med?.weekdays || []); $('#medicine-dialog').showModal(); }
  async function saveMedicine(e) { e.preventDefault(); const button = $('#medicine-save'); const frequency = $('#med-frequency').value, times = $('#med-times').value.split(',').map(t => t.trim()).filter(Boolean), weekdays = $$('#weekday-picker input:checked').map(n => Number(n.value)); if ((frequency === 'WEEKLY' || frequency === 'CUSTOM') && !weekdays.length) { $('#form-error').textContent = 'Choose at least one day.'; return; } if (times.some(t => !/^([01]\d|2[0-3]):[0-5]\d$/.test(t)) || new Set(times).size !== times.length) { $('#form-error').textContent = 'Use unique 24-hour times, such as 08:00, 20:00.'; return; } const body = { name: $('#med-name').value.trim(), dosage: $('#med-dose').value.trim(), frequency, times, weekdays, startDate: $('#med-start').value, endDate: $('#med-end').value, instructions: $('#med-instructions').value.trim() }, id = $('#medicine-id').value; try { setBusy(button, true); await api(`/medications${id ? `/${id}` : ''}`, { method: id ? 'PUT' : 'POST', body: JSON.stringify(body) }); $('#medicine-dialog').close(); await loadData(); toast(id ? 'Medicine updated.' : 'Medicine added.'); } catch (err) { $('#form-error').textContent = err.message; } finally { setBusy(button, false); } }
  async function changeDose(id, status) { try { await api(`/adherence/${id}/${status.toLowerCase()}`, { method: 'POST' }); await loadData(); toast(status === 'TAKEN' ? 'Dose marked as taken.' : 'Dose marked as skipped.'); } catch (e) { toast(e.message, true); } }
  async function logout() { try { await api('/auth/logout', { method: 'POST' }); } catch { /* Session may already be expired. */ } state = { user: null, medications: [], today: [], history: [], analytics: null, patients: [] }; showAuth('login'); location.hash = 'landing'; }
  async function notifications() { if (!('Notification' in window)) return toast('Browser notifications are unavailable here.', true); const result = await Notification.requestPermission(); renderHeader(); if (result !== 'granted') toast('Notifications were not enabled.', true); }
  function bind() {
    document.addEventListener('click', async e => { const auth = e.target.closest('[data-auth-view]'); if (auth) showAuth(auth.dataset.authView); const nav = e.target.closest('[data-view]'); if (nav) { e.preventDefault(); location.hash = nav.dataset.view; } if (e.target.closest('[data-open-med-form]')) openMedicine(); if (e.target.closest('[data-close-dialog]')) $('#medicine-dialog').close(); const dose = e.target.closest('[data-dose]'); if (dose) changeDose(dose.dataset.dose, dose.dataset.status); const edit = e.target.closest('[data-edit]'); if (edit) openMedicine(state.medications.find(m => m._id === edit.dataset.edit)); const toggle = e.target.closest('[data-toggle]'); if (toggle) { const med = state.medications.find(m => m._id === toggle.dataset.toggle); if (med) { try { await api(`/medications/${med._id}`, { method: 'PUT', body: JSON.stringify({ ...med, isActive: !med.isActive }) }); await loadData(); } catch (err) { toast(err.message, true); } } } const revoke = e.target.closest('[data-revoke]'); if (revoke) { try { await api(`/caregiver/connections/${revoke.dataset.revoke}`, { method: 'DELETE' }); await loadData(); renderCaregiver(); toast('Access removed.'); } catch (err) { toast(err.message, true); } } });
    $('#login-form').addEventListener('submit', async e => { e.preventDefault(); const b = e.submitter; $('#login-error').textContent = ''; try { setBusy(b, true); const r = await api('/auth/login', { method: 'POST', body: JSON.stringify({ email: $('#login-email').value, password: $('#login-password').value }) }); state.user = r.user; await loadData(); showApp(); route(); } catch (err) { state.user = null; showAuth('login'); $('#login-error').textContent = err.message; } finally { setBusy(b, false); } });
    $('#register-form').addEventListener('submit', async e => { e.preventDefault(); const b = e.submitter; $('#register-error').textContent = ''; try { setBusy(b, true); const r = await api('/auth/register', { method: 'POST', body: JSON.stringify({ name: $('#register-name').value, email: $('#register-email').value, password: $('#register-password').value, role: $('#register-role').value, timezone: Intl.DateTimeFormat().resolvedOptions().timeZone || 'UTC' }) }); state.user = r.user; await loadData(); showApp(); route(); } catch (err) { state.user = null; showAuth('register'); $('#register-error').textContent = err.message; } finally { setBusy(b, false); } });
    $('#medicine-form').addEventListener('submit', saveMedicine); $('#confirm-dialog').addEventListener('close', async e => { const id = e.currentTarget.dataset.id; if (e.currentTarget.returnValue === 'confirm' && id) { try { await api(`/medications/${id}`, { method: 'DELETE' }); await loadData(); toast('Medicine removed from your active schedule.'); } catch (err) { toast(err.message, true); } } }); $('#status-filter').addEventListener('change', renderHistory); $('#date-filter').addEventListener('change', renderHistory);
    $('#profile-form').addEventListener('submit', async e => { e.preventDefault(); try { const r = await api('/profile', { method: 'PUT', body: JSON.stringify({ name: $('#profile-name').value, timezone: $('#timezone').value }) }); state.user = r.user; render(); toast('Profile updated.'); } catch (err) { toast(err.message, true); } });
    $('#invite-form').addEventListener('submit', async e => { e.preventDefault(); const b = e.submitter; $('#invite-result').textContent = ''; try { setBusy(b, true); const r = await api('/caregiver/invite', { method: 'POST', body: JSON.stringify({ email: $('#invite-email').value }) }); $('#invite-result').textContent = `Share this one-time token securely: ${r.invitation.token}`; e.currentTarget.reset(); await renderCaregiver(); } catch (err) { $('#invite-result').textContent = err.message; } finally { setBusy(b, false); } });
    $('#accept-invite-form').addEventListener('submit', async e => { e.preventDefault(); $('#caregiver-error').textContent = ''; try { await api('/caregiver/accept', { method: 'POST', body: JSON.stringify({ token: $('#invite-token').value.trim() }) }); e.currentTarget.reset(); await loadData(); toast('Caregiver access accepted.'); } catch (err) { $('#caregiver-error').textContent = err.message; } });
    $('#logout-btn').addEventListener('click', logout); $('#mobile-signout').addEventListener('click', logout); $('#profile-shortcut').addEventListener('click', () => { location.hash = 'profile'; }); $('#notification-btn').addEventListener('click', notifications); $('#notification-settings').addEventListener('click', notifications); $('#menu-btn').addEventListener('click', () => { $('#more-menu').hidden = !$('#more-menu').hidden; }); $('#more-btn').addEventListener('click', () => { $('#more-menu').hidden = !$('#more-menu').hidden; }); window.addEventListener('hashchange', route);
    document.addEventListener('click', e => { const del = e.target.closest('[data-delete]'); if (del) { $('#confirm-dialog').dataset.id = del.dataset.delete; $('#confirm-dialog').showModal(); } });
    document.addEventListener('click', async e => { const patient = e.target.closest('[data-patient]'); if (!patient) return; try { const result = await api(`/caregiver/patient/${patient.dataset.patient}`); $('#next-dose').innerHTML = `<div class="reminder-card"><strong>${escapeHTML(result.patient.name)}</strong><span>${result.summary.taken} taken of ${result.summary.scheduled} scheduled today${result.summary.adherence == null ? '' : ` · ${result.summary.adherence}% adherence`}</span></div>`; } catch (error) { toast(error.message, true); } });
  }
  async function init() { bind(); initWeekdays(); try { const r = await api('/auth/me'); state.user = r.user; await loadData(); showApp(); route(); } catch (e) { state.user = null; showAuth(location.hash === '#register' ? 'register' : location.hash === '#login' ? 'login' : 'landing'); } }
  init();
})();
